// <auto-generated />
using System;
using CatSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatSharp.Data.Migrations
{
    [DbContext(typeof(CatSharpContext))]
    partial class CatSharpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("CatSharp.Data.Entities.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Name");

                    b.HasKey("CatId");

                    b.ToTable("cats");
                });

            modelBuilder.Entity("CatSharp.Data.Entities.Weight", b =>
                {
                    b.Property<int>("WeightId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CatId");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Grams");

                    b.HasKey("WeightId");

                    b.HasIndex("CatId");

                    b.ToTable("weights");
                });

            modelBuilder.Entity("CatSharp.Data.Entities.Weight", b =>
                {
                    b.HasOne("CatSharp.Data.Entities.Cat", "Cat")
                        .WithMany("Weights")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
